spring.application.name=ms-produto
#server.port = 8081


spring.profiles.active = dev
spring.jpa.open-in-view = false

# http://localhost:8080/swagger-ui/index.html
# JSON Format: http://localhost/v3/api/api-docs
